version: '3.4'
services:       
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: simulacao_juros
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080    
    networks:
      - backend 

  db-migrations:  
    image: db-migrations
    container_name: db-migrations
    restart: always
    build: 
        context: db-migrations
        dockerfile: Dockerfile
    working_dir: /
    environment:
        TZ: GMT
    command: mvn clean -f /db-migration/pom.xml clean install -P prod
    networks:
      - backend
    depends_on:
      - mysqldb
    links:
      - mysqldb         
      
  ms-cliente:  
    image: ms-cliente
    container_name: ms-cliente
    restart: always
    build: 
        context: back-end/ms-cliente
        dockerfile: Dockerfile
    working_dir: /
    environment:
        TZ: GMT
    ports:
      - "7001:7001"
    command: mvn spring-boot:run
    networks:
      - backend
      - frontend
    depends_on:
      - mysqldb
    links:
      - mysqldb         
      
  emprestimo-app:
    image: emprestimo-app
    build: 
        context: front-end
        dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - ms-cliente
    networks:
      - frontend    
      - backend      
      
volumes:
  db-data:      
      
networks:
    backend:
    frontend:
